### PR TITLE
feat: Avoid breaking changes for FC-0012 project

### PR DESCRIPTION
**Pull request by shadinaif**
Avoid breaking changes for FC-0012 project

Refs: FC-0012 OEP-58

This PR is the final polish for everything we made in https://github.com/openedx/RecommenderXBlock/pull/65 and https://github.com/openedx/RecommenderXBlock/pull/66

Here we do two things:

**Avoid Breaking Changes:**
* Revert changes made on `.tx/config`. The file is not actually used by Atlas, and changing it will affect local Transifix work while the project is still in-progress
* Move all local translations to `conf/locale` and convert `translations` into a symbolic link to `conf/locale`. The reason behind that is to comply with [openedx-translations](https://github.com/openedx/openedx-translations) mechanism that requires translation files to be in `conf/locale` directory. This fix will avoid the need to modify `find` commands [here](https://github.com/openedx/openedx-translations/blob/b85fafbac85e7c57fd8f11d75b15f10338ac1d7e/.github/workflows/extract-translation-source-files.yml#L85)
* Make the translation command `make extract_translations` build a file named `django.po` instead of `text.po`. And create a symbolic link from `text.po` to `django.po`. This is because [openedx-translations](https://github.com/openedx/openedx-translations) requires `django.po` as the name of the file. And it must be a valid file (not a link) because it uses `git add` [here](https://github.com/openedx/openedx-translations/blob/b85fafbac85e7c57fd8f11d75b15f10338ac1d7e/.github/workflows/extract-translation-source-files.yml#L100)

**Conver mako to Django Template:**
Before this PR; `${_(` HTML texts are not being extracted by `i18n_tool extract`. Because these files are Mako, not Django Template. We have two options:
* [discarded option] Add mako configuration file and fix `make extract_translations` to concatenate `mako.po` into `django.po`
* [the thing this PR does] convert Mako code to Django Template since Mako is discouraged by edx lately

- [x] Tested on local tutor to ensure that everything renders fine
- [x] Tested on local tutor to ensure that local translation still works

References
----------

This pull request is part of the [FC-0012 project](https://openedx.atlassian.net/l/cp/XGS0iCcQ) which is sparked by the [Translation Infrastructure update OEP-58](https://open-edx-proposals.readthedocs.io/en/latest/architectural-decisions/oep-0058-arch-translations-management.html#specification).

Check the links above for full information about the overall project.

Internalization is being rearchitected in Open edX Python, XBlock, Micro-frontend, and other projects. There are a number of immediately visible changes:
 - Remove source and language translations from the repositories, hence no `.json`, `.po` or `.mo` files will be committed into the repos.
 - Add standardized `make extract_translations` in all repositories
 - Push user-facing messages strings into [openedx/openedx-translations](https://github.com/openedx/openedx-translations/).
 - Integrate root repositories with [openedx/openedx-atlas](https://github.com/openedx/openedx-atlas/) to pull translations on build/deploy time

Breaking Changes
----------------

One of the primary goals of the project is to **avoid breaking changes**. If you noticed any suspicious code, please raise your concern. But before that, please know the strategy we're following to avoid breaking changes

**For XBlocks:**
 - The standard translation path must be `conf/locale`. Therefore, we are creating a link from `conf/locale` to `translations` so Atlas can find the path without disrupting the current way of having translations locally within the XBlocks
 - [openedx-translations](https://github.com/openedx/openedx-translations) will have a related PR that adds the XBlock to the pipeline. This will not affect the current way of managing/updating translations
 - At the end of the project, a clear change log will be added and all translations will be handled by Atlas. Thus, the local translation will be removed from the repo within the version bump
 - A notification for the community will be published to ensure that everyone knows why translations directories are removed from all repos

### CODE REVIEW

**Comment by openedx-webhooks** [comment]
Thanks for the pull request, @shadinaif!  Please note that it may take us up to several weeks or months to complete a review and merge your PR.

Feel free to add as much of the following information to the ticket as you can:
- supporting documentation
- [Open edX discussion forum threads](https://discuss.openedx.org/)
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).


Please let us know once your PR is ready for our review and all tests are green.

**Review by OmarIthawi — APPROVED** [review]

**Review by brian-smith-tcril — APPROVED** [review]

**Comment by brian-smith-tcril** [comment]
This seems like a reasonable solution to me, but there are a few things that aren't clear from the PR comment:
* What do you mean by "traditional translation mechanism"? Transifex bot directly committing to this repo?
* How does #65 make that useless? What does it no longer do?
* How does this PR fix that?

Adding a bit more context will be very helpful for anyone who sees this PR in the future and is curious as to what was going on.

**Comment by shadinaif** [comment]
@OmarIthawi please review the PR now. I've added detailed context to help you in the review

@OmarIthawi @brian-smith-tcril , I've tested this PR and now I can see my [openedx-translations testing PR](https://github.com/Zeit-Labs/openedx-translations/pull/8/files) generating a [valid translation PR](https://github.com/Zeit-Labs/openedx-translations/pull/8) 🥲

**Comment by shadinaif** [comment]
Sorry that the previous PR description was vague @brian-smith-tcril . Please check it now!

**Comment by OmarIthawi** [comment]
Thanks @shadinaif. Removing Mako is great!

Sorry, but did you test the latest changes on devstack? I don't see that mentioned in the PR description.

I'll give it another review next week, unless someone beats me to it.

**Comment by shadinaif** [comment]
Thank you @OmarIthawi  Added a small fix, it's now working smoothly on local tutor. I've tested HTML translation, works fine. But JS is rendering English all the time, no translation is made. I suspect it's related to i18n service not being linked properly for JS. Fixing that would be in another PR anyway

**Comment by OmarIthawi** [comment]
> Thank you @OmarIthawi Added a small fix, it's now working smoothly on local tutor. Checkboxes added to the PR description white_check_mark
> 
> I've tested HTML translation, works fine. But JS is rendering English all the time, no translation is made. I suspect it's related to i18n service not being linked properly for JS. Fixing that would be in another PR anyway. Nothing is broken, the _**new**_ translation is not being processed

I'm fine with the missing translations for JS. It's a relatively easy fix. Thanks @shadinaif! Look good to me.

**Review by brian-smith-tcril — APPROVED** [review]
:shipit:

**Comment by openedx-webhooks** [comment]
@shadinaif 🎉 Your pull request was merged!  Please take a moment  to [answer a two question survey](https://docs.google.com/forms/d/e/1FAIpQLSceJOyGJ6JOzfy6lyR3T7EW_71OWUnNQXp68Fymsk3MkNoSDg/viewform?usp=pp_url&entry.1671973413=openedx/RecommenderXBlock&entry.867055334=https://github.com/openedx/RecommenderXBlock/pull/68&entry.1484655318=https://github.com/shadinaif&entry.752974735=2023-03-31+05:07&entry.1917517419=2023-04-10+19:56&entry.2133058324=Yes) so we can improve your experience in the future.

**Pull request merged**
